name: ligo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23
  - scipy=1.10
  - matplotlib=3.7
  - h5py=3.8
  - pandas=1.5
  - decorator=4.4
  - ipykernel=6.29
  - jupyterlab=4.2
